### ISSUE TITLE
Page speed optimization

### ISSUE THREAD

**Issue by erjigit17** [metarhia/Example#162]
1. Eliminate render-blocking resources:
      1.1 google fonts "/css?family=Share+Tech+Mono"
      transfer the fonts to the server or apply the system fonts
      1.2 use preload for  /console.css

2. Enable text compression. 
    it would be good to use brotli compress

3. Use modern HTTP/2

**Comment by tshemsedinov** [comment]
1. This example is not about front-end, it shows server-side platform and access to it from browser, so client-side optimizations are not a goal for us. Moreover we serve static files because it is comfortable for developers and as a source for supply static files to cdn.
2. Ditto
3. We are going to implement HTTP/2 transport provider for `metacom` and add its support in `impress` but it is not critical because we use `websocket` over `htts` for `rpc`, so connection is permanent and there is no overhead for cryptography handshakes, etc.
