### ISSUE TITLE
Bug upload is not working

### ISSUE THREAD

**Issue by Kaskyi** [metarhia/Example#212]
Steps:
1. git clone ... && node server 
1. open localhost:8000 in a browser
1. write `upload` 
2. select a file
1. get an error in the server console
1. empty file at the `application/resources` folder 

Server console:
```
8:53  W2   log     127.0.0.1        files/upload
13:58:53  W2   error   127.0.0.1        GET     /api    400     400     Error: Stream -2097281614 is not initialized
  WsChannel.binary (/node_modules/metacom/lib/channel.js:159:23)
  WebSocket.<anonymous> (/node_modules/metacom/lib/ws.js:10:26)
  WebSocket.emit (node:events:390:28)
  Receiver.receiverOnMessage (/node_modules/ws/lib/websocket.js:1180:20)
  Receiver.emit (node:events:390:28)
  Receiver.dataMessage (/node_modules/ws/lib/receiver.js:526:14)
  Receiver.getData (/node_modules/ws/lib/receiver.js:459:17)
  Receiver.startLoop (/node_modules/ws/lib/receiver.js:158:22)
  Receiver._write (/node_modules/ws/lib/receiver.js:84:10)
  writeOrBuffer (node:internal/streams/writable:389:12)
13:58:54  W1   debug   Reload: /resources/icon.svg
13:58:57  W2   debug   Heap: 11 Mb of 12 Mb, ext: 2 Mb
13:58:57  W3   debug   Heap: 10 Mb of 12 Mb, ext: 2 Mb
13:58:57  W2   debug   Contexts: 5, detached: 0
13:58:57  W3   debug   Contexts: 5, detached: 0
13:58:57  W5   debug   Heap: 10 Mb of 12 Mb, ext: 2 Mb
13:58:57  W5   debug   Contexts: 5, detached: 0
13:58:57  W1   debug   Heap: 10 Mb of 12 Mb, ext: 2 Mb
13:58:57  W1   debug   Contexts: 5, detached: 0
13:58:57  W4   debug   Heap: 10 Mb of 12 Mb, ext: 2 Mb
13:58:57  W4   debug   Contexts: 5, detached: 0
```

Env:
```
(base) ➜ Example git:(master) ✗ node -v
npmv16.13.0
(base) ➜ Example git:(master) ✗ npm -v
8.1.0
```

ws client:
```
{"stream":1,"name":"icon.svg","size":1454}
{"call":5,"files/upload":{"streamId":1,"name":"icon.svg"}}
Binary Message
{"stream":1,"status":"end"}
{"callback":-2097281614,"error":{"message":"Stream -2097281614 is not initialized","code":400}}
```

**Comment by Kaskyi** [comment]
Workaround:

[/node_modules/metacom/lib/server.js](https://github.com/metarhia/metacom/blob/master/lib/server.js)
```js
45: this.ws.on('connection', (connection, req) => {
46:      connection.binaryType = 'arraybuffer';
```

[/node_modules/metacom/lib/client.js](https://github.com/metarhia/metacom/blob/master/lib/client.js)
```js
 22+: this.socket.binaryType = 'arraybuffer';
```

[/node_modules/metacom/lib/streams.js](https://github.com/metarhia/metacom/blob/master/lib/streams.js)
```js
29:  static decode(arrayBuffer) {
30:    const chunkView = new Uint8Array(arrayBuffer);
```

**Comment by KLarpen** [comment]
As of today the issue is still exists but not on a server side. Workaround from above is outdated due to massive changes in metacom. Currently the issue in client side code at this repository: 

https://github.com/metarhia/Example/blob/2435b8e643af3fc4a62fea1f3f20bdedc1e1d9c1/application/static/console.js#L187-L193

`streamId` isn't exists in return contract of `application.metacom.createBlobUploader` from

https://github.com/metarhia/Example/blob/2435b8e643af3fc4a62fea1f3f20bdedc1e1d9c1/application/static/metacom.js#L74-L75

Current state at the `metacom` repository is the same https://github.com/metarhia/metacom/blob/acb90a6d8cb358fe1db9e28cec8f9b4a8107cffc/dist/metacom.js#L76-L77
